// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSk1d1yuF3mZCMMmKMH5wSpmzWUMKvaA',
    appId: '1:481558429511:web:43573c29f94ab5dd661662',
    messagingSenderId: '481558429511',
    projectId: 'fir-test-bdb32',
    authDomain: 'fir-test-bdb32.firebaseapp.com',
    databaseURL: 'https://fir-test-bdb32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-bdb32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddeTkrtODbQLPPAnQK15vjII-ixWfOsM',
    appId: '1:481558429511:android:a0bd2235a9842485661662',
    messagingSenderId: '481558429511',
    projectId: 'fir-test-bdb32',
    databaseURL: 'https://fir-test-bdb32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-bdb32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYRpL3KoXbdZNzaOmB-HTB-2e_m8yOXM',
    appId: '1:481558429511:ios:11c03084d9c8d2d7661662',
    messagingSenderId: '481558429511',
    projectId: 'fir-test-bdb32',
    databaseURL: 'https://fir-test-bdb32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-bdb32.appspot.com',
    iosBundleId: 'com.example.bottomnavigationv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYRpL3KoXbdZNzaOmB-HTB-2e_m8yOXM',
    appId: '1:481558429511:ios:11c03084d9c8d2d7661662',
    messagingSenderId: '481558429511',
    projectId: 'fir-test-bdb32',
    databaseURL: 'https://fir-test-bdb32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-bdb32.appspot.com',
    iosBundleId: 'com.example.bottomnavigationv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdSk1d1yuF3mZCMMmKMH5wSpmzWUMKvaA',
    appId: '1:481558429511:web:cc642b4c0f30f2b7661662',
    messagingSenderId: '481558429511',
    projectId: 'fir-test-bdb32',
    authDomain: 'fir-test-bdb32.firebaseapp.com',
    databaseURL: 'https://fir-test-bdb32-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-bdb32.appspot.com',
  );
}
